---
services:
  gameserver:
    image: ghcr.io/forgesparks/docker-linuxgsm:latest
    restart: unless-stopped
    environment:
      GAMESERVER: fctrserver
    volumes:
      - data:/data
    ports:
      - 34197:34197/udp
volumes:
  data:
